name: lazygit
description: A simple terminal UI for git commands.
homepage: https://github.com/jesseduffield/lazygit
licenses:
  - MIT
languages: []
categories: []

source:
  id: pkg:github.com/jesseduffield/lazygit@v0.43.1
  asset:
    - target: darwin_x64
      file: lazygit_{{ version | strip_prefix "v" }}_Darwin_x86_64.tar.gz
      bin: lazygit
    - target: darwin_arm64
      file: lazygit_{{ version | strip_prefix "v" }}_Darwin_arm64.tar.gz
      bin: lazygit
    - target: linux_x86
      file: lazygit_{{ version | strip_prefix "v" }}_Linux_32-bit.tar.gz
      bin: lazygit
    - target: linux_x64
      file: lazygit_{{ version | strip_prefix "v" }}_Linux_x86_64.tar.gz
      bin: lazygit
    - target: linux_arm64
      file: lazygit_{{ version | strip_prefix "v" }}_Linux_arm64.tar.gz
      bin: lazygit
    - target: win_x86
      file: lazygit_{{ version | strip_prefix "v" }}_Windows_32-bit.zip
      bin: lazygit.exe
    - target: win_x64
      file: lazygit_{{ version | strip_prefix "v" }}_Windows_x86_64.zip
      file: lazygit.exe
    - target: win_arm64
      file: lazygit_{{ version | strip_prefix "v" }}_Windows_arm64.zip
      file: lazygit.exe

bin:
  lazygit: "{{source.asset.bin}}"
