name: yazi
description: Blazing fast terminal file manager written in Rust, based on async I/O.
homepage: https://github.com/sxyazi/yazi
licenses:
  - MIT
languages: []
categories: []
source:
  id: pkg:github/sxyazi/yazi@v0.3.0
  asset:
    - target: darwin_x64
      file: yazi-x86_64-apple-darwin.zip
      bin_yazi: yazi
      bin_ya: ya
    - target: darwin_arm64
      file: yazi-aarch64-apple-darwin.zip
      bin_yazi: yazi
      bin_ya: ya
    - target: linux_x64
      file: yazi-x86_64-unknown-linux-gnu.zip
      bin_yazi: yazi
      bin_ya: ya
    - target: linux_arm64
      file: yazi-aarch64-unknown-linux-gnu.zip
      bin_yazi: yazi
      bin_ya: ya
    - target: win_x64
      file: yazi-x86_64-pc-windows-msvc.zip
      bin_yazi: yazi.exe
      bin_ya: ya.exe
    - target: win_arm64
      file: yazi-aarch64-pc-windows-msvc.zip
      bin_yazi: yazi.exe
      bin_ya: ya.exe
bin:
  yazi: "{{source.asset.bin_yazi}}"
  ya: "{{source.asset.bin_ya}"
