name: yazi
description: Blazing fast terminal file manager written in Rust, based on async I/O.
homepage: https://github.com/sxyazi/yazi
licenses:
  - MIT
languages: []
categories: []
source:
  id: pkg:github/sxyazi/yazi@v0.3.2
  asset:
    - target: darwin_x64
      file: yazi-x86_64-apple-darwin.zip
      bin:
        yazi: yazi-x86_64-apple-darwin/yazi
        ya: yazi-x86_64-apple-darwin/ya
    - target: darwin_arm64
      file: yazi-aarch64-apple-darwin.zip
      bin:
        yazi: yazi-aarch64-apple-darwin/yazi
        ya: yazi-aarch64-apple-darwin/ya
    - target: linux_x64
      file: yazi-x86_64-unknown-linux-gnu.zip
      bin:
        yazi: yazi-x86_64-unknown-linux-gnu/yazi
        ya: yazi-x86_64-unknown-linux-gnu/ya
    - target: linux_arm64
      file: yazi-aarch64-unknown-linux-gnu.zip
      bin:
        yazi: yazi-aarch64-unknown-linux-gnu/yazi
        ya: yazi-aarch64-unknown-linux-gnu/ya
    - target: win_x64
      file: yazi-x86_64-pc-windows-msvc.zip
      bin:
        yazi: yazi-x86_64-pc-windows-msvc/yazi.exe
        ya: yazi-x86_64-pc-windows-msvc/ya.exe
    - target: win_arm64
      file: yazi-aarch64-pc-windows-msvc.zip
      bin:
        yazi: yazi-aarch64-pc-windows-msvc/yazi.exe
        ya: yazi-aarch64-pc-windows-msvc/ya.exe
bin:
  yazi: "{{source.asset.bin.yazi}}"
  ya: "{{source.asset.bin.ya}}"
