---
name: Actionlint

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
