---
name: Package tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Space-separated list of package definitions to test.
        required: true

jobs:
  lint:
    name: Registry lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: icefed/mason-actions/registry-lint@v1
        with:
          packages: ${{ github.event.inputs.packages }}

  test:
    name: Package tests
    needs: lint
    uses: icefed/mason-actions/.github/workflows/package-tests.yaml@v1
    with:
      packages: ${{ github.event.inputs.packages }}
